### ISSUE TITLE
Don't puke when adb fails to reboot into fastmode

### ISSUE THREAD

**Issue by jlongster** [jonallengriffin/b2gautomation#1]
I bricked my phone by accidentally trying to flash the wrong build, so it was stuck in fastboot mode. I couldn't flash it with flash.sh because it dies if adb doesn't work, which is wrong (mwu confirmed this in #b2g).

The line is: https://github.com/jonallengriffin/b2gautomation/blob/master/b2gautomation/devices/nexus-s/flash.sh#L38

It should silently fail.

**Comment by jonallengriffin** [comment]
Fixed with https://github.com/jonallengriffin/b2gautomation/commit/fdbc4ec65ae56507c5fea38b244272d25fe3f2c7; will be tomorrow's nightly.
